# Generated by Django 4.1.13 on 2024-04-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240402_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monmodele',
            name='mon_champ',
        ),
        migrations.AddField(
            model_name='monmodele',
            name='champ_entier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monmodele',
            name='champ_texte',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
