# Generated by Django 4.1.13 on 2024-04-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_monmodele_mon_champ_monmodele_champ_entier_and_more'),
    ]

    operations = [
    ]
